services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile_backend
    container_name: back
    volumes:
      - ./backend:/code

    tty: true
    stdin_open: true

    restart: "no"

    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb

    working_dir: /code
    command: ["bash"]

    ports:
      - 3000:3000

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile_frontend
    container_name: front
    volumes:
      - ./frontend:/frontend

    tty: true
    stdin_open: true

    restart: "no"

    working_dir: /frontend
    command: ["bash"]
    #command: ["bash", "-c", "npm install && npm run dev"]

    ports:
      - 8000:8000


  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db:/code
      #- db-data:/var/lib/postgresql/data

    working_dir: /code

    ports:
      - 5432:5432

volumes:
  db-data: