services:
  node-backend:
    image: dev-node
    build: .
    container_name: dev-back
    volumes:
      - ./backend:/backend

    tty: true
    stdin_open: true

    restart: "no"

    environment:
      PGHOST: dev-db
      PGUSER: postgres
      PGDATABASE: mydb
      PGPASSWORD: password
      PGPORT: 5432 

    working_dir: /backend
    #command: ["bash"]
    command: ["bash", "-c", "npm install && npm run dev"]

    ports:
      - 3000:3000

  node-frontend:
    image: dev-node
    build: .
    container_name: dev-front
    volumes:
      - ./frontend:/frontend

    tty: true
    stdin_open: true

    restart: "no"

    working_dir: /frontend
    #command: ["bash"]
    command: ["bash", "-c", "npm install && npm run dev"]

    ports:
      - 8000:8000


  db:
    image: postgres
    container_name: dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - ./db:/db
      #- db-data:/var/lib/postgresql/data

    working_dir: /db

    ports:
      - 5432:5432

volumes:
  db-data: